Traceback (most recent call last):
  File "./test_otool.py", line 61, in <module>
    ft_test_dir(dir)
  File "./test_otool.py", line 52, in ft_test_dir
    ft_test_file(dir + "/" + file)
  File "./test_otool.py", line 34, in ft_test_file
    isExe = run_cmd_output(file)
  File "./test_otool.py", line 26, in run_cmd_output
    pipe = cmd.Popen(c.split(), stdout=out, stderr=err)
IOError: [Errno 9] Bad file descriptor
